### ISSUE TITLE
Any plan to add an option to select the font?

### ISSUE THREAD

**Issue by cxuerui** [digimezzo/Knowte#25]
The default chinese font display is not good. Thank you.

**Comment by EMLVIRUS** [comment]
> an option to modify the font

Do you mean the Windows API to utilize fonts intalled in `%system%/fonts`?

**Comment by Cxuerui** [comment]
@EMLVIRUS  I mean the edit interface, may be because it does not support the [Mactype](http://www.mactype.net/) rendering.
The following is a comparison picture：
![2017-05-01_153057](https://cloud.githubusercontent.com/assets/24670630/25574926/433f36e6-2e85-11e7-9763-dbaec9562c34.png)

The onenote2010 rendered by the [Mactype](http://www.mactype.net/) looks better.
