### ISSUE TITLE
release  a version in linux

### ISSUE THREAD

**Issue by c101088** [digimezzo/Knowte#34]
thanks for this cool konwte ,have any plan to develop a version on linux,maybe ubuntu something .

**Comment by digimezzo** [comment]
You're welcome. Knowte is actually inspired by Tomboy notes, which is available on Linux. I created Knowte because Tomboy is not optimal on Windows. I however don't know the current development status of Tomboy. Hopefully it hasn't been abandoned.
As for a Knowte on Linux. I'd gladly create one. But the UI frameworks don't appeal to me. They're stuck in another era graphically and usage wise.

**Comment by digimezzo** [comment]
This is implemented by https://github.com/digimezzo/knowte-electron
